import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;


public class AnaSayfa extends javax.swing.JFrame {
    int mpx;
    int mpy;
    Arkaplan arkaplan;
    String seciliTur = null;
    static ArrayList<String> filmListesi;
    int alangenislik = 0;
    int alanyukseklik = 0;
    int kaymaMiktari = 0;
    int scrollp = 0;
    
    boolean gostergehazir = false;
    /**
     * Creates new form AnaSayfa
     */
    public AnaSayfa() {
        setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        //Dimension dm = new Dimension(1366, 768);
        //setPreferredSize(dm);
        
        
       
        filmListesi = new ArrayList<String>();
        tumFilmleriGetir();
        
        initComponents();
        
        //aramaSonuclari.setEditable(false);
        //aramaSonuclari.setLineWrap(true);
        //aramaSonuclari.setWrapStyleWord(true);
        
        gostergeKullanici.setText(Netflix.mevcutKullaniciAd);
        
        //Arama İşlemi İçin
       aramaKutusu.getDocument().addDocumentListener(new DocumentListener() {
           @Override
            public void changedUpdate(DocumentEvent e) {
                aramaKutusuDegisti(e);
            }
            @Override
            public void insertUpdate(DocumentEvent e) {
                aramaKutusuDegisti(e);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
              aramaKutusuDegisti(e);
            }
            
            private void aramaKutusuDegisti(DocumentEvent e){
                //System.out.println(aramaKutusu.getText());
                //arama fonkunu calistircaz
                aramaYap(aramaKutusu.getText());
            }
        });
       
       //En başta tüm filmleri listelemek istiyoruz.
       
       
       //System.out.println(filmTutucu.getWidth() + " " + filmTutucu.getHeight());
       //filmTutucu.setLayout(null);
       
       //System.out.println(filmTutucu.getWidth());
       //filmTutucu.add(new FilmKutusu(300+10,0,null));
       
       filmleriGoster();
       
       arkaplan = new Arkaplan(this.getWidth(), this.getHeight());
        arkaplan.setBounds(0,0,this.getWidth(), this.getHeight());
        this.add(arkaplan);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        gostergeKullanici = new javax.swing.JLabel();
        oturumuKapat = new javax.swing.JLabel();
        aramaKutusu = new javax.swing.JTextField();
        turSecimi = new javax.swing.JComboBox<>();
        filmTutucu = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        titlebar = new javax.swing.JLabel();
        maxmin = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(8);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        gostergeKullanici.setForeground(new java.awt.Color(255, 255, 255));
        gostergeKullanici.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gostergeKullanici.setText("kullaniciAdi");

        oturumuKapat.setForeground(new java.awt.Color(255, 255, 255));
        oturumuKapat.setText("Oturumu Kapat");
        oturumuKapat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oturumuKapatMouseClicked(evt);
            }
        });

        aramaKutusu.setForeground(new java.awt.Color(255, 255, 255));

        turSecimi.setForeground(new java.awt.Color(255, 255, 255));
        turSecimi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tümünü Görüntüle", "Aksiyon ve Macera", "Bilim Kurgu ve Fantastik Yapımlar", "Romantik", "Drama", "Çocuk ve Aile", "Belgesel", "Komedi", "Korku", "Bilim ve Doğa", "Gerilim", "Anime", "Reality Program" }));
        turSecimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turSecimiActionPerformed(evt);
            }
        });

        filmTutucu.setBackground(new java.awt.Color(102, 255, 102));
        filmTutucu.setForeground(new java.awt.Color(255, 51, 51));
        filmTutucu.setOpaque(false);

        javax.swing.GroupLayout filmTutucuLayout = new javax.swing.GroupLayout(filmTutucu);
        filmTutucu.setLayout(filmTutucuLayout);
        filmTutucuLayout.setHorizontalGroup(
            filmTutucuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        filmTutucuLayout.setVerticalGroup(
            filmTutucuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        scroll.setBackground(new java.awt.Color(255, 51, 51));
        scroll.setBlockIncrement(100);
        scroll.setForeground(new java.awt.Color(153, 0, 204));
        scroll.setMaximum(10);
        scroll.setUnitIncrement(10);
        scroll.setVisibleAmount(8);
        scroll.setOpaque(false);
        scroll.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                scrollMouseWheelMoved(evt);
            }
        });
        scroll.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                scrollAdjustmentValueChanged(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("İsme göre arama:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Türe göre arama:");

        titlebar.setBackground(new java.awt.Color(255, 51, 51));
        titlebar.setOpaque(true);
        titlebar.setPreferredSize(new java.awt.Dimension(0, 20));
        titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titlebarMouseDragged(evt);
            }
        });
        titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titlebarMousePressed(evt);
            }
        });

        maxmin.setBackground(new java.awt.Color(255, 51, 51));
        maxmin.setForeground(new java.awt.Color(255, 255, 255));
        maxmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxmin.setText("_");
        maxmin.setOpaque(true);
        maxmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                maxminMousePressed(evt);
            }
        });

        close.setBackground(new java.awt.Color(255, 51, 51));
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("x");
        close.setOpaque(true);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimgui/logo2.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filmTutucu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(turSecimi, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aramaKutusu, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 49, Short.MAX_VALUE)
                        .addComponent(gostergeKullanici, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oturumuKapat, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(maxmin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maxmin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel2)
                        .addComponent(turSecimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(aramaKutusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(oturumuKapat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gostergeKullanici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filmTutucu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oturumuKapatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oturumuKapatMouseClicked
        // TODO add your handling code here:
        
        //Kullanici bilgisi elimizde Netflix.mevcutKullanici - Netflix.mevcutKullaniciAd
        Netflix.kullaniciGirisi = new KullaniciGirisi();
        Netflix.kullaniciGirisi.setLocationRelativeTo(null);
        Netflix.kullaniciGirisi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_oturumuKapatMouseClicked

    private void turSecimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turSecimiActionPerformed
        // TODO add your handling code here:
        // TODO TUR ARATMADAN DEVAM ET
        
        seciliTur = (String)turSecimi.getSelectedItem();
        
        if(seciliTur == "Tümünü Görüntüle"){
            tumFilmleriGetir();
            filmleriGoster();
            return;
        }
        
        filmListesi.removeAll(filmListesi);
        
        
        String sonuclar = "";
        
        if(seciliTur != null){
            try{
            Veritabani.stmt = (Statement)Veritabani.con.createStatement();
            String sorgu = "SELECT ProgramAdi FROM programtur WHERE TurAdi = \""+seciliTur+"\" ";
            Veritabani.rs = Veritabani.stmt.executeQuery(sorgu);
            while(Veritabani.rs.next()){
                //sonuclar += Veritabani.rs.getString(1) + " \n";
                filmListesi.add(Veritabani.rs.getString(1));
            }
            }catch(SQLException ex){
            
            }
        }
        
        //film listesi değişecek
        
        
        //aramaSonuclari.setText(sonuclar);
        //Filmleri tekrar göstercez
        filmleriGoster();
        
    }//GEN-LAST:event_turSecimiActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized

    }//GEN-LAST:event_formComponentResized

    private void scrollAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_scrollAdjustmentValueChanged
        // TODO add your handling code here:
        //Filmleri yerlestircem
        kaymaMiktari = evt.getValue();

        int degisim = evt.getValue() - scrollp;

        if(gostergehazir == true){
            //System.out.println("girmemesi gerek");
            for(int i = 0; i < filmListesi.size(); i++){
                //System.out.println("girmemesi gerek");
                Component cp =filmTutucu.getComponent(i);

                cp.setBounds(cp.getX() , cp.getY()-degisim , 300, 160);
            }
        }
        //System.out.println(degisim);
        //System.out.println(kaymaMiktari);
        scrollp = evt.getValue();
    }//GEN-LAST:event_scrollAdjustmentValueChanged

    private void scrollMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_scrollMouseWheelMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_scrollMouseWheelMoved

    private void titlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMouseDragged
        // TODO add your handling code here:
        int px = evt.getXOnScreen();
        int py = evt.getYOnScreen();

        //this.setLocation(px - mpx, py - mpy);
    }//GEN-LAST:event_titlebarMouseDragged

    private void titlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMousePressed
        // TODO add your handling code here:
        mpx = evt.getX();
        mpy = evt.getY();
    }//GEN-LAST:event_titlebarMousePressed

    private void maxminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxminMousePressed
        // TODO add your handling code here:

        setExtendedState(JFrame.ICONIFIED);

        /*
        if(maksimum == false){
            setExtendedState(JFrame.MAXIMIZED_BOTH);
            maksimum = true;
        }else{
            //setState(JFrame.ICONIFIED);
            setExtendedState(JFrame.NORMAL);
            maksimum = false;
        }
        */
    }//GEN-LAST:event_maxminMousePressed

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMousePressed

     void aramaYap(String aranan){
         filmListesi.removeAll(filmListesi);
        //Yazi her degistiginde calisacak ve sonuclari kutuya aktaracak
            String sonuclar = "";
            //aranana göre arıcaz
            //if(aranan != "" && aranan.length() > 0){
            try{
            Veritabani.stmt = (Statement)Veritabani.con.createStatement();
            //String sorgu = "SELECT distinct ProgramAdi FROM programtur WHERE (ProgramAdi LIKE '%"+aranan+"%') or (TurAdi LIKE '%"+aranan+"%')";
            String sorgu = "SELECT distinct ProgramAdi FROM programtur WHERE (ProgramAdi LIKE '%"+aranan+"%')";
            Veritabani.rs = Veritabani.stmt.executeQuery(sorgu);
            while(Veritabani.rs.next()){
                //sonuclar += Veritabani.rs.getString(1) + " \n";
                filmListesi.add(Veritabani.rs.getString(1));
            }
            }catch(SQLException ex){
            
            }
            
            //aramaSonuclari.setText(sonuclar);
                //System.out.println("Bu istek aramadan geldi");
            filmleriGoster();
            //filmTutucu.repaint();
            //}
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaSayfa().setVisible(true);
            }
        });
    }
    
    void filmleriGoster(){
        //Tüm elemanlari sildik.
        
        filmTutucu.removeAll();
        
        
        //System.out.println("Elemanlar temizlendi...");
        //System.out.println(filmTutucu.getComponents().length);
        //System.out.println(filmListesi.size());
        
        int alangenislik = filmTutucu.getWidth();
        int alanyukseklik = filmTutucu.getHeight();
        //System.out.println(alangenislik + " " + alanyukseklik);
        int kutugenislik = 300;
        int kutuyukseklik = 160;
        int yatayKonum = 0;
        int dikeyKonum = 10;
        int bosluk = 10;
        int yerlesimgenislik = 0;
        int yerlesimyukseklik = 0;
        //int engenis = 0;
        
        for(int i = 0; i < filmListesi.size(); i++){
            //System.out.println("test");
            FilmKutusu fk = new FilmKutusu(yatayKonum, dikeyKonum, filmListesi.get(i));
            
            
            yatayKonum += kutugenislik+bosluk;
               if(yatayKonum - 10 > yerlesimgenislik){
                    yerlesimgenislik = yatayKonum - 10;
                    //System.out.println("yg: " + yerlesimgenislik);
                }
            
            if((yatayKonum+kutugenislik) >= filmTutucu.getWidth()){
                yatayKonum = 0;
                dikeyKonum += kutuyukseklik+bosluk;
            }
            
            yerlesimyukseklik = dikeyKonum ;
            
            //Scrollu ayarliyoruz
            gostergehazir = false;
            //System.out.println("burdayimmm");
            //System.out.println(yerlesimyukseklik);
            scroll.setMinimum((alanyukseklik-kutuyukseklik-10));
            scroll.setMaximum((yerlesimyukseklik));

            
            filmTutucu.add(fk);
            
            gostergehazir = true;
           filmTutucu.repaint();
        }
        
        int hizalamamiktari = (alangenislik - yerlesimgenislik)/2;
        //System.out.println(alangenislik);
        //System.out.println(yerlesimgenislik);
        //System.out.println(hizalamamiktari);
        //Hizalama
        for(int i = 0; i < filmListesi.size(); i++){
            Component cp =filmTutucu.getComponent(i);
            cp.setBounds(cp.getX() + hizalamamiktari, cp.getY(), kutugenislik, kutuyukseklik);
            //System.out.println(cp.getX());
        }
        
      
         
         
    }
    
    void tumFilmleriGetir(){
        filmListesi.removeAll(filmListesi);
        try{
            Veritabani.stmt = (Statement)Veritabani.con.createStatement();
            String sorgu = "SELECT distinct ProgramAdi FROM programtur";
            Veritabani.rs = Veritabani.stmt.executeQuery(sorgu);
            while(Veritabani.rs.next()){
                filmListesi.add(Veritabani.rs.getString(1));
            }
            }catch(SQLException ex){
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aramaKutusu;
    private javax.swing.JLabel close;
    private javax.swing.JPanel filmTutucu;
    private javax.swing.JLabel gostergeKullanici;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel maxmin;
    private javax.swing.JLabel oturumuKapat;
    private javax.swing.JScrollBar scroll;
    private javax.swing.JLabel titlebar;
    private javax.swing.JComboBox<String> turSecimi;
    // End of variables declaration//GEN-END:variables
}
