import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JFrame;

//BU SINIFTA NETBEANS GUI EDITOR ILE AUTO GENERATE KULLANILMISTIR

public class KullaniciGirisi extends javax.swing.JFrame {
    Arkaplan arkaplan;
    int mpx;
    int mpy;
    
    boolean maksimum = false;
    
    public KullaniciGirisi() {
        initComponents();
        
        /*
        try {
            
            BufferedImage img = null;
            img = ImageIO.read(new File("data/arkaplanTile.jpg"));
            JLabel arkaplan = new JLabel(new ImageIcon(img));
            arkaplan.setBounds(0, 0, 600, 600);
            //System.out.println(img);
            add(arkaplan);

        } catch (IOException ex) {
            System.out.println("arkaplan hata");
            Logger.getLogger(KullaniciGirisi.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        
        arkaplan = new Arkaplan(this.getWidth(), this.getHeight());
        arkaplan.setBounds(0,0,this.getWidth(), this.getHeight());
        //add(arkaplan);
        this.add(arkaplan);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        girdiEPosta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        butonGirisYap = new javax.swing.JButton();
        labelUyeOl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        titlebar = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        hesapUyari = new javax.swing.JLabel();
        sifreUyari = new javax.swing.JLabel();
        maxmin = new javax.swing.JLabel();
        girdiSifre = new javax.swing.JPasswordField();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setResizable(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("E-Posta:");

        girdiEPosta.setToolTipText("E-Posta adresinizi giriniz.");
        girdiEPosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girdiEPostaActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Şifre:");

        butonGirisYap.setForeground(new java.awt.Color(204, 255, 255));
        butonGirisYap.setText("Giriş Yap");
        butonGirisYap.setToolTipText("Giriş yapmak için tıklayınız.");
        butonGirisYap.setOpaque(false);
        butonGirisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonGirisYapActionPerformed(evt);
            }
        });

        labelUyeOl.setForeground(new java.awt.Color(255, 255, 255));
        labelUyeOl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUyeOl.setText("Üye Ol");
        labelUyeOl.setToolTipText("");
        labelUyeOl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelUyeOlMouseClicked(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimgui/logo.png"))); // NOI18N

        titlebar.setBackground(new java.awt.Color(255, 51, 51));
        titlebar.setOpaque(true);
        titlebar.setPreferredSize(new java.awt.Dimension(0, 20));
        titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titlebarMouseDragged(evt);
            }
        });
        titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titlebarMousePressed(evt);
            }
        });

        close.setBackground(new java.awt.Color(255, 51, 51));
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("x");
        close.setOpaque(true);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
        });

        hesapUyari.setForeground(new java.awt.Color(255, 51, 51));

        sifreUyari.setForeground(new java.awt.Color(255, 51, 51));
        sifreUyari.setToolTipText("");

        maxmin.setBackground(new java.awt.Color(255, 51, 51));
        maxmin.setForeground(new java.awt.Color(255, 255, 255));
        maxmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxmin.setText("_");
        maxmin.setOpaque(true);
        maxmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                maxminMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(maxmin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUyeOl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(girdiEPosta)
                            .addComponent(butonGirisYap, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(girdiSifre))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hesapUyari)
                    .addComponent(sifreUyari))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addComponent(maxmin, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                    .addComponent(titlebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hesapUyari)
                        .addComponent(girdiEPosta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sifreUyari)
                    .addComponent(jLabel2)
                    .addComponent(girdiSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butonGirisYap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUyeOl)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void girdiEPostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girdiEPostaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_girdiEPostaActionPerformed

    private void butonGirisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonGirisYapActionPerformed

        //Giriş işlemi
        //Giris İslemi Veritabani üzerinde yapılıyor.
        
        // kutudaki epostayi al
        // kutudaki sifreyi al
        // sorgu yapcaz
        // Eğer 1 kayıt geliyor ise o kayit epostasi ile anasayfaya yönlendircez
        String eposta = girdiEPosta.getText();
        String sifre = girdiSifre.getText();
       
        String girisSorgu = "SELECT kullaniciEPosta,kullaniciAdi FROM kullanici WHERE KullaniciEPosta = \'" + eposta + "\' and KullaniciSifre = \'"+sifre+"\'";
        String hesapDurumuSorgu ="SELECT kullaniciEPosta,kullaniciAdi FROM kullanici WHERE KullaniciEPosta = \'"+eposta+"\' and KullaniciSifre != \'"+sifre+"\'";     
        hesapUyari.setText("");
        sifreUyari.setText("");
        
        String girisYapanEPosta;
        String girisYapanAd;
         boolean girisYapildi = false;
         boolean hesapMevcutMu = false;
        try {
            Veritabani.stmt = (Statement)Veritabani.con.createStatement();
            Veritabani.rs = Veritabani.stmt.executeQuery(hesapDurumuSorgu);
            while(Veritabani.rs.next()){
               hesapMevcutMu = true;
                sifreUyari.setText("Şifreniz yanlış!");
                girdiSifre.setText("");
                //System.out.println("Eposta doğru şifre yanlış!");
            }
            
            Veritabani.stmt = (Statement)Veritabani.con.createStatement();
            Veritabani.rs = Veritabani.stmt.executeQuery(girisSorgu);
            while(Veritabani.rs.next()){   
                //Döngüye girildiyse giris yapilmistir.
                girisYapildi = true;
                girisYapanEPosta = Veritabani.rs.getString("kullaniciEPosta");
                girisYapanAd = Veritabani.rs.getString("kullaniciAdi");
                
                System.out.println(girisYapanEPosta + " giris yapmistir!");
                
                Netflix.mevcutKullanici = girisYapanEPosta;
                Netflix.mevcutKullaniciAd = girisYapanAd;
                Netflix.anaSayfa = new AnaSayfa();
                Netflix.anaSayfa.setLocationRelativeTo(null);
                Netflix.anaSayfa.setVisible(true);
                this.dispose();
                
                //Bu Noktada diğer arayüze geçicez
            }
            
            if(hesapMevcutMu == false && girisYapildi == false){
                hesapUyari.setText("Böyle bir hesap bulunamadı!");
                Netflix.kayitSorusu = new KayitSorusu();
                Netflix.kayitSorusu.setLocationRelativeTo(null);
                Netflix.kayitSorusu.setVisible(true);
            }
            
    
        } catch (SQLException ex) {
            Logger.getLogger(KullaniciGirisi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butonGirisYapActionPerformed

    private void labelUyeOlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUyeOlMouseClicked
        // TODO add your handling code here:
        Netflix.kullaniciKayit = new KullaniciKayit();
        Netflix.kullaniciKayit.setLocationRelativeTo(null);
        Netflix.kullaniciKayit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelUyeOlMouseClicked

    private void titlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMouseDragged
        // TODO add your handling code here:
        int px = evt.getXOnScreen();
        int py = evt.getYOnScreen();
        
        this.setLocation(px - mpx, py - mpy);
    }//GEN-LAST:event_titlebarMouseDragged

    private void titlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMousePressed
        // TODO add your handling code here:
        mpx = evt.getX();
        mpy = evt.getY();
    }//GEN-LAST:event_titlebarMousePressed

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMousePressed

    private void maxminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxminMousePressed
        // TODO add your handling code here:
        
        setExtendedState(JFrame.ICONIFIED);
        
        /*
        if(maksimum == false){
            setExtendedState(JFrame.MAXIMIZED_BOTH);
            maksimum = true;
        }else{
            //setState(JFrame.ICONIFIED);
            setExtendedState(JFrame.NORMAL);
            maksimum = false;
        }
        */
    }//GEN-LAST:event_maxminMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullaniciGirisi().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonGirisYap;
    private javax.swing.JLabel close;
    private javax.swing.JTextField girdiEPosta;
    private javax.swing.JPasswordField girdiSifre;
    private javax.swing.JLabel hesapUyari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelUyeOl;
    private javax.swing.JLabel maxmin;
    private javax.swing.JLabel sifreUyari;
    private javax.swing.JLabel titlebar;
    // End of variables declaration//GEN-END:variables
}
