
import java.sql.SQLException;
import java.util.*;
import java.awt.*;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;

public class KullaniciKayit2 extends javax.swing.JFrame {
    Arkaplan arkaplan;
    int mpx;
    int mpy;
    
    String eposta;
    String ad;
    String sifre;
    String tarih;
    
    //3 tür seçtircez
    static ArrayList<String> secilenler;
    
    //Seçim durumları
    boolean durumaksiyonmacera = false;
    boolean durumbilimkurgu = false;
    boolean durumromantik = false;
    boolean durumbilimdoga = false;
    boolean durumdrama = false;
    boolean durumcocukaile = false;
    boolean durumgerilim = false;
    boolean durumbelgesel = false;
    boolean durumkorku = false;
    boolean durumanime = false;
    boolean durumkomedi = false;
    boolean durumreality = false;
    
    
    /**
     * Creates new form KullaniciKayit2
     */
    public KullaniciKayit2(String eposta, String ad, String sifre, String tarih) {
        initComponents();
        
        arkaplan = new Arkaplan(this.getWidth(), this.getHeight());
        arkaplan.setBounds(0,0,this.getWidth(), this.getHeight());
        //add(arkaplan);
        this.add(arkaplan);
        
        this.eposta = eposta;
        this.ad = ad;
        this.sifre = sifre;
        this.tarih = tarih;
        secilenler = new ArrayList<String>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        kayitTamamla = new javax.swing.JButton();
        aksiyonmacera = new javax.swing.JLabel();
        bilimdoga = new javax.swing.JLabel();
        gerilim = new javax.swing.JLabel();
        anime = new javax.swing.JLabel();
        bilimkurgu = new javax.swing.JLabel();
        drama = new javax.swing.JLabel();
        belgesel = new javax.swing.JLabel();
        komedi = new javax.swing.JLabel();
        romantik = new javax.swing.JLabel();
        cocukaile = new javax.swing.JLabel();
        korku = new javax.swing.JLabel();
        reality = new javax.swing.JLabel();
        uyariTurSecim = new javax.swing.JLabel();
        titlebar = new javax.swing.JLabel();
        maxmin = new javax.swing.JLabel();
        close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("En Sevdiğiniz 3 Tür");

        kayitTamamla.setForeground(new java.awt.Color(255, 255, 255));
        kayitTamamla.setText("Kayıt işlemini tamamla");
        kayitTamamla.setOpaque(false);
        kayitTamamla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayitTamamlaActionPerformed(evt);
            }
        });

        aksiyonmacera.setForeground(new java.awt.Color(204, 204, 204));
        aksiyonmacera.setText("Aksiyon ve Macera");
        aksiyonmacera.setToolTipText("");
        aksiyonmacera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aksiyonmaceraMouseClicked(evt);
            }
        });

        bilimdoga.setForeground(new java.awt.Color(204, 204, 204));
        bilimdoga.setText("Bilim ve Doğa");
        bilimdoga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bilimdogaMouseClicked(evt);
            }
        });

        gerilim.setForeground(new java.awt.Color(204, 204, 204));
        gerilim.setText("Gerilim");
        gerilim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gerilimMouseClicked(evt);
            }
        });

        anime.setForeground(new java.awt.Color(204, 204, 204));
        anime.setText("Anime");
        anime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                animeMouseClicked(evt);
            }
        });

        bilimkurgu.setForeground(new java.awt.Color(204, 204, 204));
        bilimkurgu.setText("Bilim Kurgu ve Fantastik");
        bilimkurgu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bilimkurguMouseClicked(evt);
            }
        });

        drama.setForeground(new java.awt.Color(204, 204, 204));
        drama.setText("Drama");
        drama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dramaMouseClicked(evt);
            }
        });

        belgesel.setForeground(new java.awt.Color(204, 204, 204));
        belgesel.setText("Belgesel");
        belgesel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                belgeselMouseClicked(evt);
            }
        });

        komedi.setForeground(new java.awt.Color(204, 204, 204));
        komedi.setText("Komedi");
        komedi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                komediMouseClicked(evt);
            }
        });

        romantik.setForeground(new java.awt.Color(204, 204, 204));
        romantik.setText("Romantik");
        romantik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                romantikMouseClicked(evt);
            }
        });

        cocukaile.setForeground(new java.awt.Color(204, 204, 204));
        cocukaile.setText("Çocuk ve Aile");
        cocukaile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cocukaileMouseClicked(evt);
            }
        });

        korku.setForeground(new java.awt.Color(204, 204, 204));
        korku.setText("Korku");
        korku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                korkuMouseClicked(evt);
            }
        });

        reality.setForeground(new java.awt.Color(204, 204, 204));
        reality.setText("Reality Program");
        reality.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                realityMouseClicked(evt);
            }
        });

        uyariTurSecim.setForeground(new java.awt.Color(255, 51, 51));

        titlebar.setBackground(new java.awt.Color(255, 51, 51));
        titlebar.setOpaque(true);
        titlebar.setPreferredSize(new java.awt.Dimension(0, 20));
        titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titlebarMouseDragged(evt);
            }
        });
        titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titlebarMousePressed(evt);
            }
        });

        maxmin.setBackground(new java.awt.Color(255, 51, 51));
        maxmin.setForeground(new java.awt.Color(255, 255, 255));
        maxmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxmin.setText("_");
        maxmin.setOpaque(true);
        maxmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                maxminMousePressed(evt);
            }
        });

        close.setBackground(new java.awt.Color(255, 51, 51));
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("x");
        close.setOpaque(true);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(maxmin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bilimkurgu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(aksiyonmacera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(romantik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(uyariTurSecim)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cocukaile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bilimdoga)
                                            .addComponent(drama, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(belgesel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(korku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(gerilim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(kayitTamamla, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reality, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(anime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(komedi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maxmin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aksiyonmacera)
                    .addComponent(bilimdoga)
                    .addComponent(gerilim)
                    .addComponent(anime))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bilimkurgu)
                    .addComponent(drama)
                    .addComponent(belgesel)
                    .addComponent(komedi))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(romantik)
                    .addComponent(cocukaile)
                    .addComponent(korku)
                    .addComponent(reality))
                .addGap(20, 20, 20)
                .addComponent(uyariTurSecim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kayitTamamla)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kayitTamamlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayitTamamlaActionPerformed
            // TODO add your handling code here:
            //3 türü kontrol edicez seçildi mi diye?
            uyariTurSecim.setText("");
            
            if(secilenler.size() == 3){
                //işlemi yapcaz
                //Kayıt işlemi başarılı bir sonraki sayfaya listeyi göndericez.
                
                String kayitSorgu = "INSERT INTO Kullanici VALUES(?,?,?,?)";
                
                try{
                Veritabani.pstmt = Veritabani.con.prepareStatement(kayitSorgu);
                Veritabani.pstmt.setString(1, this.eposta);
                Veritabani.pstmt.setString(2, this.ad);
                Veritabani.pstmt.setString(3, this.sifre);
                Veritabani.pstmt.setString(4, this.tarih);

                Veritabani.pstmt.executeUpdate();
                    System.out.println("tamamlandi!");
                //Veritabani.pstmt.executeQuery()
                }
                catch(Exception e){
                        System.out.println(e);
                }
                
                Netflix.oneriSayfasi = new OneriSayfasi(secilenler, this.eposta, this.ad);
                Netflix.oneriSayfasi.setLocationRelativeTo(null);
                Netflix.oneriSayfasi.setVisible(true);
                this.dispose();
                
            }else{
                uyariTurSecim.setText("Lütfen 3 adet tür seçiniz!");
            }
            
            //Kontrol yapmama gerek yok çünkü bilgiler zaten kontrol edildi.
            //Bilgileri kayit2 ye göndericez. burada
            //System.out.println(eposta);
            //System.out.println(ad);
            //System.out.println(sifre);
            //System.out.println(tarih);
            
            
    }//GEN-LAST:event_kayitTamamlaActionPerformed

    private void aksiyonmaceraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aksiyonmaceraMouseClicked
        secimKontrol(aksiyonmacera, durumaksiyonmacera, "Aksiyon ve Macera");
    }//GEN-LAST:event_aksiyonmaceraMouseClicked

    private void bilimkurguMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilimkurguMouseClicked
        // TODO add your handling code here:
        secimKontrol(bilimkurgu, durumbilimkurgu, "Bilim Kurgu ve Fantastik Yapımlar");
        
    }//GEN-LAST:event_bilimkurguMouseClicked

    private void romantikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_romantikMouseClicked
        // TODO add your handling code here:
        secimKontrol(romantik, durumromantik, "Romantik");
    }//GEN-LAST:event_romantikMouseClicked

    private void bilimdogaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilimdogaMouseClicked
        // TODO add your handling code here:
        secimKontrol(bilimdoga, durumbilimdoga, "Bilim ve Doğa");
    }//GEN-LAST:event_bilimdogaMouseClicked

    private void dramaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dramaMouseClicked
        // TODO add your handling code here:
        secimKontrol(drama, durumdrama, "Drama");
    }//GEN-LAST:event_dramaMouseClicked

    private void cocukaileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cocukaileMouseClicked
        // TODO add your handling code here:
        secimKontrol(cocukaile, durumcocukaile, "Çocuk ve Aile");
        
    }//GEN-LAST:event_cocukaileMouseClicked

    private void gerilimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerilimMouseClicked
        // TODO add your handling code here:
        secimKontrol(gerilim, durumgerilim, "Gerilim");
    }//GEN-LAST:event_gerilimMouseClicked

    private void belgeselMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_belgeselMouseClicked
        // TODO add your handling code here:
        secimKontrol(belgesel, durumbelgesel, "Belgesel");
    }//GEN-LAST:event_belgeselMouseClicked

    private void korkuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_korkuMouseClicked
        // TODO add your handling code here:
        secimKontrol(korku, durumkorku, "Korku");
    }//GEN-LAST:event_korkuMouseClicked

    private void animeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_animeMouseClicked
        // TODO add your handling code here:
        secimKontrol(anime, durumanime, "Anime");
    }//GEN-LAST:event_animeMouseClicked

    private void komediMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_komediMouseClicked
        // TODO add your handling code here:
        secimKontrol(komedi, durumkomedi, "Komedi");
    }//GEN-LAST:event_komediMouseClicked

    private void realityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realityMouseClicked
        // TODO add your handling code here:
        secimKontrol(reality, durumreality, "Reality Program");
    }//GEN-LAST:event_realityMouseClicked

    private void titlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMouseDragged
        // TODO add your handling code here:
        int px = evt.getXOnScreen();
        int py = evt.getYOnScreen();

        this.setLocation(px - mpx, py - mpy);
    }//GEN-LAST:event_titlebarMouseDragged

    private void titlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMousePressed
        // TODO add your handling code here:
        mpx = evt.getX();
        mpy = evt.getY();
    }//GEN-LAST:event_titlebarMousePressed

    private void maxminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxminMousePressed
        // TODO add your handling code here:

        setExtendedState(JFrame.ICONIFIED);

        /*
        if(maksimum == false){
            setExtendedState(JFrame.MAXIMIZED_BOTH);
            maksimum = true;
        }else{
            //setState(JFrame.ICONIFIED);
            setExtendedState(JFrame.NORMAL);
            maksimum = false;
        }
        */
    }//GEN-LAST:event_maxminMousePressed

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMousePressed

    static void secimKontrol(JLabel label, boolean kontrol, String dbisim){
        if(secilenler.contains(dbisim)){
            //içeriyorsa silicem
            secilenler.remove(dbisim);
            kontrol = false;
        }else{
            //içermiyorsa kontrol yapıcam boyutu 3 mü değilse eklicem
            if(secilenler.size() < 3){
                secilenler.add(dbisim);
                kontrol = true;
            }else{
                return;
            }
            
        }
        
        //kontrol = !kontrol;
        
        if(kontrol){
            //label.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
            label.setForeground(Color.RED);
        }else{
            //label.setBorder(BorderFactory.createLineBorder(Color.RED, 0));
            label.setForeground(new Color(204,204,204));
        }
        
        /*
        System.out.println("\n\n");
        for(int i = 0; i < secilenler.size(); i++){
            System.out.println(secilenler.get(i));
        }
        */
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciKayit2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciKayit2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciKayit2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciKayit2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(
            new Runnable() {
                public void run() {
                    new KullaniciKayit2(null, null, null, null).setVisible(true);
                }
            }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aksiyonmacera;
    private javax.swing.JLabel anime;
    private javax.swing.JLabel belgesel;
    private javax.swing.JLabel bilimdoga;
    private javax.swing.JLabel bilimkurgu;
    private javax.swing.JLabel close;
    private javax.swing.JLabel cocukaile;
    private javax.swing.JLabel drama;
    private javax.swing.JLabel gerilim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kayitTamamla;
    private javax.swing.JLabel komedi;
    private javax.swing.JLabel korku;
    private javax.swing.JLabel maxmin;
    private javax.swing.JLabel reality;
    private javax.swing.JLabel romantik;
    private javax.swing.JLabel titlebar;
    private javax.swing.JLabel uyariTurSecim;
    // End of variables declaration//GEN-END:variables
}
