
import java.util.ArrayList;
import javax.swing.JFrame;

public class OneriSayfasi extends javax.swing.JFrame {
    int mpx;
    int mpy;
    Arkaplan arkaplan;
    String mevcutKullanici;
    String mevcutKullaniciAd;
    ArrayList<String> secilenler;
    static String film1_1 = null;
    static String film1_2 = null;
    static String film2_1 = null;
    static String film2_2 = null;
    static String film3_1 = null;
    static String film3_2 = null;
    static String tur1;
    static String tur2;
    static String tur3;
    static float film1_1p,film1_2p,film2_1p,film2_2p,film3_1p,film3_2p;
    /**
     * Creates new form OneriSayfasi
     */
    public OneriSayfasi(ArrayList<String> secilenler, String mevcutKullanici, String mevcutKullaniciAd ) {
        tur1 = secilenler.get(0);
        tur2 = secilenler.get(1);
        tur3 = secilenler.get(2);
        initComponents();
        
        arkaplan = new Arkaplan(this.getWidth(), this.getHeight());
        arkaplan.setBounds(0,0,this.getWidth(), this.getHeight());
        //add(arkaplan);
        this.add(arkaplan);
        
        this.secilenler = secilenler;
        this.mevcutKullanici = mevcutKullanici;
        this.mevcutKullaniciAd = mevcutKullaniciAd;
        
        for(String s:this.secilenler){
            System.out.println(s);
        }
        
        onerilenFilmleriGetir(this.secilenler);
        
        onerilenFilmler.setEditable(false);
        onerilenFilmler.setLineWrap(true);
        onerilenFilmler.setWrapStyleWord(true);
        onerilenFilmler.setText(tur1+" kategorisinin 1. en iyi filmi "+film1_1+" Puan: "+film1_1p+"\n"+tur1+" kategorisinin 2. en iyi filmi "+film1_2+" Puan: "+film1_2p+"\n"+tur2+" kategorisinin 1. en iyi filmi "+film2_1+" Puan: "+film2_1p+"\n"
        +tur2+" kategorisinin 2. en iyi filmi "+film2_2+" Puan: "+film2_2p+"\n"+tur3+" kategorisinin 1. en iyi filmi "+film3_1+" Puan: "+film3_1p+"\n"+tur3+" kategorisinin 2. en iyi filmi "+film3_2+" Puan: "+film3_2p+"\n");
        //Bunu artık labeller üzerinde yapıcaz.
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        anaSayfayaGit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        titlebar = new javax.swing.JLabel();
        maxmin = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        onerilenFilmler = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("İşte sizin için seçtiğimiz bazı yapımlar.");

        anaSayfayaGit.setForeground(new java.awt.Color(255, 51, 51));
        anaSayfayaGit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anaSayfayaGit.setText("Beni anasayfaya götür");
        anaSayfayaGit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anaSayfayaGitMouseClicked(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Kayıt işlemi başarı ile tamamlandı!");
        jLabel4.setToolTipText("");

        titlebar.setBackground(new java.awt.Color(255, 51, 51));
        titlebar.setOpaque(true);
        titlebar.setPreferredSize(new java.awt.Dimension(0, 20));
        titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titlebarMouseDragged(evt);
            }
        });
        titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titlebarMousePressed(evt);
            }
        });

        maxmin.setBackground(new java.awt.Color(255, 51, 51));
        maxmin.setForeground(new java.awt.Color(255, 255, 255));
        maxmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxmin.setText("_");
        maxmin.setOpaque(true);
        maxmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                maxminMousePressed(evt);
            }
        });

        close.setBackground(new java.awt.Color(255, 51, 51));
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("x");
        close.setOpaque(true);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
        });

        onerilenFilmler.setColumns(20);
        onerilenFilmler.setForeground(new java.awt.Color(255, 255, 255));
        onerilenFilmler.setRows(5);
        jScrollPane1.setViewportView(onerilenFilmler);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titlebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(maxmin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(anaSayfayaGit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane1))))
                                .addGap(0, 13, Short.MAX_VALUE)))))
                .addGap(0, 0, 0)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maxmin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anaSayfayaGit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anaSayfayaGitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anaSayfayaGitMouseClicked
        // TODO add your handling code here:
        
        Netflix.mevcutKullanici = mevcutKullanici;
        Netflix.mevcutKullaniciAd = mevcutKullaniciAd;
        Netflix.anaSayfa = new AnaSayfa();
        Netflix.anaSayfa.setLocationRelativeTo(null);
        Netflix.anaSayfa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_anaSayfayaGitMouseClicked

    private void titlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMouseDragged
        // TODO add your handling code here:
        int px = evt.getXOnScreen();
        int py = evt.getYOnScreen();

        this.setLocation(px - mpx, py - mpy);
    }//GEN-LAST:event_titlebarMouseDragged

    private void titlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMousePressed
        // TODO add your handling code here:
        mpx = evt.getX();
        mpy = evt.getY();
    }//GEN-LAST:event_titlebarMousePressed

    private void maxminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxminMousePressed
        // TODO add your handling code here:

        setExtendedState(JFrame.ICONIFIED);

        /*
        if(maksimum == false){
            setExtendedState(JFrame.MAXIMIZED_BOTH);
            maksimum = true;
        }else{
            //setState(JFrame.ICONIFIED);
            setExtendedState(JFrame.NORMAL);
            maksimum = false;
        }
        */
    }//GEN-LAST:event_maxminMousePressed

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OneriSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OneriSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OneriSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OneriSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OneriSayfasi(null, null, null).setVisible(true);
            }
        });
    }
    
    public static void onerilenFilmleriGetir(ArrayList<String> secilenler){
        
        
        String sorgufilm1oneri = "select kp.ProgramAdi, AVG(kp.Puan)  from kullaniciProgram kp, programtur pt where pt.TurAdi = \""+tur1+"\" and pt.ProgramAdi = kp.ProgramAdi GROUP BY kp.ProgramAdi ORDER BY AVG(kp.Puan) desc limit 2";
        String sorgufilm2oneri = "select kp.ProgramAdi, AVG(kp.Puan)  from kullaniciProgram kp, programtur pt where pt.TurAdi = \""+tur2+"\" and pt.ProgramAdi = kp.ProgramAdi GROUP BY kp.ProgramAdi ORDER BY AVG(kp.Puan) desc limit 2";
        String sorgufilm3oneri = "select kp.ProgramAdi, AVG(kp.Puan)  from kullaniciProgram kp, programtur pt where pt.TurAdi = \""+tur3+"\" and pt.ProgramAdi = kp.ProgramAdi GROUP BY kp.ProgramAdi ORDER BY AVG(kp.Puan) desc limit 2";
        
        
        
                
        try{
            //Veritabani.pstmt = Veritabani.con.prepareStatement(kayitSorgu);
            //Veritabani.pstmt.setString(1, this.eposta);
            //Veritabani.pstmt.setString(2, this.ad);
            //Veritabani.pstmt.setString(3, this.sifre);
            //Veritabani.pstmt.setString(4, this.tarih);
            // Veritabani.pstmt.executeUpdate();
            
            Veritabani.stmt = Veritabani.con.createStatement();
            Veritabani.rs = Veritabani.stmt.executeQuery(sorgufilm1oneri);
            int sayac = 0;
            while(Veritabani.rs.next()){
                if(sayac == 0){
                    film1_1 = Veritabani.rs.getString(1);
                    film1_1p = Veritabani.rs.getFloat(2);
                }
                
                if(sayac == 1){
                    film1_2 = Veritabani.rs.getString(1);
                    film1_2p = Veritabani.rs.getFloat(2);
                }
                
                sayac++;
            }
            
            Veritabani.stmt = Veritabani.con.createStatement();
            Veritabani.rs = Veritabani.stmt.executeQuery(sorgufilm2oneri);
            sayac = 0;
            while(Veritabani.rs.next()){
                if(sayac == 0){
                    film2_1 = Veritabani.rs.getString(1);
                    film2_1p = Veritabani.rs.getFloat(2);
                }
                
                if(sayac == 1){
                    film2_2 = Veritabani.rs.getString(1);
                    film2_2p = Veritabani.rs.getFloat(2);
                }
                
                sayac++;
            }
            
            Veritabani.stmt = Veritabani.con.createStatement();
            Veritabani.rs = Veritabani.stmt.executeQuery(sorgufilm3oneri);
            sayac = 0;
            while(Veritabani.rs.next()){
                if(sayac == 0){
                    film3_1 = Veritabani.rs.getString(1);
                    film3_1p = Veritabani.rs.getFloat(2);
                }
                
                if(sayac == 1){
                    film3_2 = Veritabani.rs.getString(1);
                    film3_2p = Veritabani.rs.getFloat(2);
                }
                
                sayac++;
            }
            
        }catch(Exception e){
        
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anaSayfayaGit;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maxmin;
    private javax.swing.JTextArea onerilenFilmler;
    private javax.swing.JLabel titlebar;
    // End of variables declaration//GEN-END:variables
}
